import { type NextPage } from "next";
import Head from "next/head";
import { Input } from "../component/input";
import { FormGroup } from "~/component/FormGroup";
import { useState } from "react";
import { api } from "~/utils/api";
import { Button } from "~/component/Button";
import Image from "next/image";

const colors = [
    'blue',
    'red',
    'green',
    'yellow',
    'white',
    'black',
    'orange',
]

 const shapes = [
    'circle',
    'square',
    'rounded',
 ]

 const styles = [
    'claymorphic',
    '3d rendered',
    'pixelated',
    'illustrated with color pencil'
 ]

const GeneratePage: NextPage = () => {


    const [form, setForm] = useState({
        prompt: "",
        color: "",
        shape: "",
        style: "",
        numberToGenerate: "1",
    });

    const [error, setError] = useState("");
    const [imagesUrl, setImagesUrl] = useState<{imageUrl: string}[]>([]);

    const generateIcon = api.generate.generateIcon.useMutation({
        onSuccess(data) {
            setImagesUrl(data);
        },
        onError(error){
            setError(error.message);
        }
    });
    function handleFormSubmit(e: React.FormEvent){
        e.preventDefault();
        setError("");
        generateIcon.mutate({
            ...form,
            numberToGenerate: parseInt(form.numberToGenerate)
        });
        // setForm((prev)=>({...prev, prompt: ""}));
    }

    function updateForm( key: string){
        return function(e: React.ChangeEvent<HTMLInputElement>){
            setForm(prev => ({
                ...prev, 
                [key]: e.target.value
            }))
        }
    }

    return (
        <>
            <Head>
                <title>Generate Icons</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="container px-8 mx-auto mt-24 flex min-h-screen flex-col gap-4">
                <h1 className="text-6xl">Generate your icons</h1>
                <p className=" text-2xl mb-12">Fill out form below to start generating your icons</p>
                <form className="flex flex-col gap-4"
                    onSubmit={handleFormSubmit} >

                    <h2>1. Describe what you want your icon to look like</h2>
                    <FormGroup className="mb-12"> 
                        <label>Prompt</label>
                        <Input value={form.prompt} required onChange={updateForm("prompt")} />
                    </FormGroup>

                    <h2>2. Pick your icon color.</h2>
                    <FormGroup className="grid grid-cols-4 mb-12"> 
                        {colors.map(color => (
                            <label key={color} className="flex gap-2 text-2xl">
                                <input type="radio" required name="color" checked={color === form.color} onChange={()=>setForm((prev)=>({...prev, color}))}></input>
                                {color}
                            </label>    
                        ))}
                    </FormGroup>

                    <h2>3. Pick your icon shape.</h2>
                    <FormGroup className="grid grid-cols-4 mb-12"> 
                        {shapes.map(shape => (
                            <label key={shape} className="flex gap-2 text-2xl">
                                <input type="radio" required name="color" checked={shape === form.shape} onChange={()=>setForm((prev)=>({...prev, shape}))}></input>
                                {shape}
                            </label>    
                        ))}
                    </FormGroup>

                    <h2>4. Pick your icon style.</h2>
                    <FormGroup className="grid grid-cols-4 mb-12"> 
                        {styles.map(style => (
                            <label key={style} className="flex gap-2 text-2xl">
                                <input type="radio" required name="color" checked={style === form.shape} onChange={()=>setForm((prev)=>({...prev, style}))}></input>
                                {style}
                            </label>    
                        ))}
                    </FormGroup>

                    <h2 className="text-xl">5. How many do you want.</h2>
                    <FormGroup className="mb-12"> 
                            <label>
                                Number of icons.
                            </label>    
                                <Input value={form.numberToGenerate} 
                                inputMode="numeric"
                                pattern="[1-9]|10"
                                type="number"
                                required
                                onChange={updateForm("numberToGenerate")}
                                >
                                </Input>
                    </FormGroup>

                    {error && (
                        <div className="bg-red-500 text-white p-8 text-xl rounded">
                            {error}
                        </div>
                    )}
                    
                    <Button isLoading={generateIcon.isLoading} disabled={generateIcon.isLoading}>Submit</Button>
                </form>
                {imagesUrl.length>0 && (
                    <>
                        <h2 className="text-xl">Your Icons</h2>
                        <section className="grid grid-cols-4 gap-4 mb-12">
                            {imagesUrl.map(({imageUrl})=>(
                                <Image 
                                    key={imageUrl}
                                    src={imageUrl} 
                                    alt="an image of your generated prompt" 
                                    width={512} 
                                    height={512} 
                                    className="w-full"
                                />
                            ))}
                        </section>

                    </>
                )}
            </main>
        </>
    );
};

export default GeneratePage;
