import { type NextPage } from "next";
import Head from "next/head";
import { Input } from "../component/input";
import { FormGroup } from "~/component/FormGroup";
import { useState } from "react";
import { api } from "~/utils/api";
import { signIn, signOut, useSession } from "next-auth/react";
import { Button } from "~/component/Button";

const GeneratePage: NextPage = () => {

    const [form, setForm] = useState({
        prompt: "",
    });

    const generateIcon = api.generate.generateIcon.useMutation();

    function handleFormSubmit(e: React.FormEvent){
        e.preventDefault();
        generateIcon.mutate({prompt: form.prompt,});
    }

    function updateForm( key: string){
        return function(e: React.ChangeEvent<HTMLInputElement>){
            setForm(prev => ({
                ...prev, 
                [key]: e.target.value
            }))
        }
    }

    const session = useSession();

    const isLoggedIn = session.data;

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-center">
                {!isLoggedIn && (
                <Button onClick={() => signIn().catch(console.error)} >LogIn</Button>
                )}
                {isLoggedIn && (
                <Button onClick={() => signOut().catch(console.error)} >LogOut</Button>
                )}
                {session.data?.user.name}
                <form className="flex flex-col gap-4"
                    onSubmit={handleFormSubmit} >
                    <FormGroup> 
                        <label>Prompt</label>
                        <Input value={form.prompt} onChange={updateForm("prompt")} />
                    </FormGroup>
                    <Button className="bg-blue-400 hover:bg-blue-500 px-4 py-2 rounded">Submit</Button>
                </form>
            </main>
        </>
    );
};

export default GeneratePage;
